/* eslint-disable @next/next/link-passhref */
import React from 'react'
import Head from 'next/head'
import * as style from '@/styles/document.module.css'
import FootV1 from '@/components/footer/footv1';
import Link from 'next/link'
import HeadV2 from '@/components/header/headv2'
import NavigationV2 from '@/components/navigation/navigationv2';
import LinksButton from '@/components/caveats/links';


export default function FAQ() {
  

  return (
    <div className={style.main}>
      <Head>
        <title>RCK - Frequently Asked Questions</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <HeadV2  title={"Documentation"} root={"/v1"}/>
      <div className={style.container}>
        <NavigationV2/>

        

        <div className={style.contentBox}>
          <p className={style.title1Text}>
            Frequently Asked Questions
          </p>
          <p className={style.boldText}>
            Where to send the smart contract of RCK?
          </p>
          <p className={style.normalText}>
            Technically, whatever wallet address you use to transact smart contract, is where you send the RCK Token.
            If you want to transfer RCK Tokens to other wallet application or wallet address, you can just make sure the network is Binance Smart Chain.
          </p>
            
        </div>
        <LinksButton/>
      </div>

      <FootV1/>
    </div>
  )
}
