/* eslint-disable @next/next/link-passhref */
import React from 'react'
import Head from 'next/head'
import * as style from '@/styles/document.module.css'
import FootV1 from '@/components/footer/footv1';
import Link from 'next/link'
import HeadV2 from '@/components/header/headv3'
import NavigationV2 from '@/components/navigation/navigationv2'
import LinksButton from '@/components/caveats/links'

export default function Tokenomiks() {
  

  return (
    <div className={style.main}>
      <Head>
        <title>RCK – RPS NFT Game Mechanics</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <HeadV2 title={"Documentation"} root={"/v1"}/>
      <div className={style.titleContainer}>
        <h1 className={style.titleText} >RPS NFT Game Mechanics</h1>
      </div>
      <div className={style.container}>
        

        <NavigationV2/>

        <div className={style.contentBox}>
          <h2 className={style.boldText}>
            How to get playing and earning?
          </h2>

          <p className={style.boldText}>
            01 Get Axesscard
          </p>


          <p className={style.tabText}>
            • You need to get your hands
            on the Axesscard (That’s an NFT btw!)
          </p>
          <p className={style.tabText}>
            • Activate the Axesscard
          </p>
          <p className={style.tabText}>
            • You can only get Axesscard
            from : Initial Private Launch
            or the RPS marketplace. In
            both places, you would need
            to buy using our RCK Token
          </p>

          <div className={style.dash}/>


          <p className={style.boldText}>
            02 Start Playing – Earn Points
          </p>
          <p className={style.tabText}>
             • Each Axesscard has a certain
            allowable number of plays
            (play count) that refreshes
            every [4] hours
          </p>
          <p className={style.tabText}>
             • Each play is simply round
            where player chooses the
            element: rock, paper or
            scissors, for each of the three
            (3) trays
          </p>
          <p className={style.tabText}>
            • The opponent’s element (real
            person’s selection) shows
            whether you win or lose
          </p>
          <p className={style.tabText}>
            • If you win, you get a point
            and experience.
          </p>
          <p className={style.tabText}>
            • If you lose, you only get
            experience.
          </p>


          <div className={style.dash}/>


          <p className={style.boldText}>
            03 Breed Variant Axcesscard
          </p>
          <p className={style.tabText}>
            • You can choose to breed an
            Axesscard to produce a
            variant once you have the
            required points and
            experience to replicate
          </p>
          <p className={style.tabText}>
            • An Axesscard must be 1st
            activated to use. The
            replicated variant’s
            characters of play count and
            experience is generated at
            random.
          </p>
          <p className={style.tabText}>
            • Likewise, each replicated
            Axesscard variant will also
            have different levels of
            reward requirements
          </p>


          <div className={style.dash}/>

          <p className={style.boldText}>
            04 Earn Rewards to RCK Token
          </p>
          <p className={style.tabText}>
            • You can choose to convert
            points to RCK instead of
            using it to breeding.
          </p>
          <p className={style.tabText}>
            • Now with RCK Token you
            have access to RCK
            ecosystem (ventures) or
            trade in the DEX where RCK
            is traded, and swap to other
            cryptos.
          </p>


          <div className={style.dash}/>

          <p className={style.boldText}>
            05 Trade Axesscards
          </p>
          <p className={style.tabText}>
            • Axesscards are NFTs. You can
            trade them in the
            marketplace
          </p>
          <p className={style.tabText}>
             • The value of the Axesscard
            may depend whether it is
            activated (known
            characteristics) or inactivated
            (unknown characteristics).
          </p>
          <p className={style.tabText}>
            • Naturally, activated Axesscard
            with more characteristics (play
            count and replication count)
            may demand higher price
            than inactivated Axesscard or
            activated Axesscard with less
            characteristics.
          </p>
          <p className={style.tabText}>
            • Players can buy and sell
            Axesscards using RCK Tokens.
          </p>

          <p className={style.normalText}>
            At the Initial Private Launch only LIMITED no. of Axesscards will be distributed!
            Thereafter, players would need to buy Axesscards in the RPS marketplace, at perhaps higher price

          </p>


          <div className={style.previewContainer}>
            
            <Link href="/v1/rpsnftgame">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>RPS NFT GAME</h4> 
              </div>
            </Link>
              
            <Link href="/v1/setupcryptowallet">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Setup Crypto Wallet</h4> 
              </div>
            </Link>

          </div>
              <LinksButton/>
        </div>

      </div>

      <FootV1/>
    </div>
  )
}
