/* eslint-disable @next/next/link-passhref */
import React from 'react'
import Head from 'next/head'
import * as style from '@/styles/document.module.css'
import FootV1 from '@/components/footer/footv1';
import Link from 'next/link'
import HeadV2 from '@/components/header/headv2'
import  NavigationV2  from '@/components/navigation/navigationv2';
import LinksButton from '@/components/caveats/links'
import ScrollButton from '@/components/buttons/scroll';

export default function AbstractAndBackdrop() {
  

  return (
    <div className={style.main}>
      <ScrollButton/>
      <Head>
        <title>RCK - Abstract And Backdrop</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <HeadV2  title={"Documentation"} root={"/v1"}/>
      <div className={style.titleContainer}>
        <h2 className={style.titleText} > What is BlockChain?</h2>
      </div>
      <div className={style.container}>
        
        <NavigationV2/>

        <div className={style.contentBox}>
          <div className={style.imageBox1}>
            <img src="/Images/Abstract/blockchain.jpg" className={style.image1}/>
          </div>
          <p className={style.boldText}>
            Bitcoin is simply a digital currency which is build using blockchain technology.
          </p>
          <p className={style.normalText}>
            This new revolutionising wave famously called web 3.0 is all around the internet. Everyone is talking about bitcoins, cryptocurrencies, blockchain. But you might be wondering what the heck blockchain is? In this blog post, i will try to explain blockchain in very basic terms which even a 5 year old can understand. Slowly as you will proceed reading I will increase little bit complexity.
          </p>
          <p className={style.normalText}>
            Blockchain Technology basically helps in Trade. Because of this technology, you can trade with anyone around the globe, without knowing about him personally and without any intermediate party (like banks or other companies).
          </p>

          <p className={style.normalText}>
            For eg: Let’s say you want to sell your smartphone. Currently you will use platform like ebay which acts as an intermediate between you and the person to whom you want to sell. The payments might be processed via some bank which will cost you or/and the other person some money. Now because of blockchain, you will be able to sell your smartphone to that person without actually involving ebay or any other bank in between. That’s blockchain explained on very basic level.
          </p>


          <div className={style.previewContainer}>
            
            <Link href="/v1/disclaimer">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Disclaimer</h4> 
              </div>
            </Link>
              
            <Link href="/v1/ourvisiontoventure">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Our Vision To Venture</h4> 
              </div>
            </Link>

          </div>
          <LinksButton/>
        </div>

      </div>

      <FootV1/>
    </div>
  )
}
