/* eslint-disable @next/next/link-passhref */
import React from 'react'
import Head from 'next/head'
import * as style from '@/styles/document.module.css'
import FootV1 from '@/components/footer/footv1';
import Link from 'next/link'
import HeadV2 from '@/components/header/headv2'
import  NavigationV2  from '@/components/navigation/navigationv2';
import LinksButton from '@/components/caveats/links'

export default function AbstractAndBackdrop() {
  

  return (
    <div className={style.main}>
      <Head>
        <title>RCK - Abstract And Backdrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeadV2  title={"Documentation"} root={"/v1"}/>
      <div className={style.titleContainer}>
        <h2 className={style.titleText} >Abstract and Backdrop</h2>
      </div>
      <div className={style.container}>
        
        <NavigationV2/>

        <div className={style.contentBox}>

          <p className={style.normalText}>
            Blockchain will has been revolutionizing our world. The enigmatic rollout of Bitcoin in early 2009 captivated the attention of technologist and
            visionaries amidst the Global Financial Crisis. This new and exciting technology has challenged the status quo and gave birth to new and “noble”
            ways of how we think about money (finance), knowledge (information), equality (access) and community (accountability & connectivity).
          </p>
          <p className={style.normalText}>
            The blockchain’s immediate popular application - Bitcoin, opened up the massive downpour of money and waves of cryptocurrencies. In
            2013, the total market value of the entire cryptocurrency was USD 1.64 billion. Even then, the greater majority was not really paying attention.
            After 8 years, that value reached USD 2.455 trillion in May 2021. That’s a 150,153% jump (1,502x) equivalent as the as 8th largest economy in
            the world. There were only 66 cryptocurrencies globally in 2013 and has since exponentially exploded to over 6k cryptos in 2020 showing a 91x
            jump (Source: Statista 2021). While the top 10% crypto makes up about 88% of the total market value of USD2 trillion (Source: Block Social), the
            sheer number of cryptocurrencies is a convincing sign that adoption and demand from the wider population is has accelerated.
          </p>

          <p className={style.boldText}>
            Where are crypto adopters?
          </p>

          <p className={style.normalText}>
            According to Statista Global Consumer Survey (2021), out of 74 countries, the third highest rates of cryptocurrency use were recorded in the Philippines.
          </p>

          <p className={style.boldText}>
            Informal Adoption.
          </p>
          <p className={style.normalText}>
            The NFT (Non-Fungible Token) craze was embraced in the Philippines via a game. Axie Infinity is now the leading NFT-based online video game in countries such as the Philippines, Indonesia and Valenzuela. The attractive model of “play-to-earn” (PtoE) quickly gained traction among the youth where the promise of playing while earning provides both necessary needs especially during the pandemic
          </p>

          <p className={style.boldText}>
            Formal Adoption.
          </p>
          <p className={style.normalText}>
            The Bangko Sentral ng Pilipinas (BSP had approved several crypto
            exchanges as "remittance and transfer companies" while the
            government leveraged the blockchain setting up blockchain app,
            bonds.ph in partnership with Unionbank. Likewise Unionbank, the
            Philippine’s 9th largest bank, had already installed a Bitcoin ATM in
            Makati in early 2019. These steps and more are convincing signals of
            the client’s widespread adoption of cryptocurrencies towards
            mainstream utilities. As the financial industry (generally) shift to where
            the investment appetite is, banks leading the charge is a telling sign
            that the shift is expected to ramp up. Even the government has
            positioned itself to harness blockchain technology to accommodate a
            more digital-crypto friendly economy.
          </p>


          <div className={style.previewContainer}>
            
            <Link href="/v1/disclaimer">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Disclaimer</h4> 
              </div>
            </Link>
              
            <Link href="/v1/ourvisiontoventure">
              <div className={style.previewBox}>
                <h4 className={style.buttonText}>Our Vision To Venture</h4> 
              </div>
            </Link>

          </div>
          <LinksButton/>
        </div>

      </div>

      <FootV1/>
    </div>
  )
}
