/* eslint-disable @next/next/link-passhref */
import React from 'react'
import Head from 'next/head'
import * as style from '@/styles/document.module.css'
import FootV1 from '@/components/footer/footv1'
import Link from 'next/link'
import HeadV2 from '@/components/header/headv2'
import NavigationV2 from '@/components/navigation/navigationv2'
import LinksButton from '@/components/caveats/links'
import ScrollButton from '@/components/buttons/scroll'


export default function Disclaimer() {


  return (
    <div className={style.main}>
      <ScrollButton/>
      <Head>
        <title>Welcome to RCK | Rock Token
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeadV2 title={"Documentation"} root={"/v1"} />


      <div className={style.titleContainer}>
        <h2 className={style.titleText}  >Get Started</h2>
      </div>

      <div className={style.container}>
        <NavigationV2/>

        

        <div className={style.contentBox}>

          <p className={style.normalText}>
            WORKING IN PROGRESS.
          </p>

          <p className={style.normalText}>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
          </p>
          <LinksButton/>
          
          
        </div>

      </div>

      <FootV1/>
    </div>
  )
}
